### ISSUE TITLE
Integrate unittest with buildbots

### ISSUE THREAD

**Issue by badb** [golemfactory/clay#1400]
Currently we have 7 separate CI tools integrated. Buildbots that produces packages for 3 OS, CircleCI to run unittest on Linux, Travis to run unittest on Mac, AppVeyor to run unittest on Windows and Shippable to run linters. 
If we are able to move unittest on buildbots (and create build only if all tests pass) then we'll significantly simplify CI architecture. 

# Main tasks
- [x] Run unit test on linux POC
- [x] Add automated installer on linux #1455 
- [x] Run unit test on mac POC
- [x] Run unit test on windows POC
- [x] Add automated installer on mac 
- [x] Run windows as service and own user #1636 
- [x] Add automated installer on windows
- [x] Add controlling build, report status
- [x] Deploy
- [x] Write nightly upload build

# Tasks from reviews and findings
- [x] Remove python 2
- [x] Update `hyperg` to `0.2.3`
- [x] remove `ipfs` after #1548 
- [x] decide on hosting
- [x] upload coverage for all builds

**Comment by maaktweluit** [comment]
Two down, one to go:

![screen shot 2017-11-14 at 13 50 56](https://user-images.githubusercontent.com/10008353/32780813-f169d994-c942-11e7-93f5-11dd6e22b163.png)

![screen shot 2017-11-14 at 13 51 08](https://user-images.githubusercontent.com/10008353/32780816-f4a0e4cc-c942-11e7-9506-06e084292920.png)

Next steps before releasing:
- python 2 to python 3
- windows unit test
- grouped build ( optional )
- decide on hosting

Added those to OP

**Comment by maaktweluit** [comment]
From the PR #1455, 3 tasks left to pickup on next update:
- Update `hyperg` to `0.2.3`
- Remove ipfs after #1548 
- upload codecov to s3

Added those to OP

**Comment by maaktweluit** [comment]
Windows blockers solved :D

![screen shot 2017-11-21 at 16 50 02](https://user-images.githubusercontent.com/10008353/33082117-4739a9fa-cedc-11e7-9788-dcc687f76699.png)

Will group all open branches and:
- Remove python2
- Remove ipfs
- Add guiding build
- Check re-build protection to not build all 3 when one fails.

**Comment by maaktweluit** [comment]
Removed IPFS and python2
Also added inno to build installer after binaries

Next steps are:
- guiding builds
- re-build protection
- coverage
- nightly repo uploads.

**Comment by maaktweluit** [comment]
Made great progress on the controlling jobs.
- structure setup and tested
- PR hook enabled
- PR approval count migrated
- enabled multiple workers per server for control builds

Next step are:
- [x] upload coverage
- [x] write nightly job
- [x] Test new status reports
- [x] Test artefacts with original version from `version.py`
- [x] Add rebuild protection on previous success of commit + platform
- [x] migrate lint job

**Comment by maaktweluit** [comment]
Made good progress on:
- Finish rebuild protection
- Adding linter tests
- Test status reports and version parsing
- Add multiple workers for production setup

Got blocked by Windows not behaving as intended:
- Installer broke on end-to-end test setup ( reported jberezanski/ChocolateyPackages issue 28 ). Made work-around so i could continue
- Windows unit tests broke on paymentkeeper, made issue #1738. Added skips for these tests for now.

Next steps are:
- [x] Hide coverage secret ( WIP )
- [x] Write nightly build ( WIP )
- [x] Merge new files required for production setup #1743 
- [x] Setup production
- [x] Link production with github

**Comment by maaktweluit** [comment]
Requested the migration this morning, Y2 will propose a transfer window.
