### ISSUE TITLE
Computation environments: Nvidia Container Runtime for Docker

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#3143]
Creating Nvidia Docker, now in testing, also includes possible bug fixes. 

- [x] Golem integration #3045
- [x] Installer: nvidia-docker dependency #3094
- [x] Docker: bundle dockerfiles for building images using binaries #3133
- [ ] Multi-GPU setup support
