### ISSUE TITLE
Architectural improvements: services as subprocesses

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/clay#3159]
- [x] decouple the transaction system module
- [ ] subprocess framework for services:
    - provides an API for service <-> core communication
    - provides an authentication mechanism
    - manages service's lifecycle (start / stop)
- [ ] move transaction system to a separate process
- [ ] move resource manager to a separate process
