### ISSUE TITLE
[WIP] Epic: Show top-ups and withdraws in the transaction history

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/clay#4172]
## Rationale
We'd like to display to the user each and every transaction that changes the balance of their GNT(B) and ETH accounts.

So far, we're registering only `Incomes` and `Payments` but we'd like to extend that with top-ups and withdraws + provide gas cost for each operation related to any transactions executed by the node in question.

### Functional specification
* [x] Ensure that SCI allows retrieval of GNT top-ups (@krigpl)
* [x] Provide persistence layer for the GNT top-ups
* [x] Implement an RPC to retrieve GNT top-ups (include it in the list of `Incomes` aka Incoming?)
* [x] Ensure that SCI allows retrieval of ETH top-ups (@Krigpl)
* [x] Provide persistence layer for the ETH top-ups
* [x] Implement an RPC to retrieve ETH top-ups (include it in the list of `Incomes` aka Incoming?)
* [x] Ensure that SCI provides a way to execute confirm callbacks on GNT withdraws -> what if Golem is stopped before the callback executes? -> or ensure that SCI allows us to catch the confirmation events in some other way... (@krigpl - `SCI::on_transaction_confirmed)
* [x] Provide persistence layer for the GNT withdraws 
* [x] Implement an RPC to retrieve GNT withdraws (include it in the list of `Payments` aka Outgoing)?
* [x] Ensure that SCI provides a way to execute confirm callbacks on ETH withdraws -> what if Golem is stopped before the callback executes? (@krigpl - `SCI::on_transaction_confirmed)
* [x] Provide persistence layer for the ETH withdraws 
* [x] Implement an RPC to retrieve ETH withdraws (include it in the list of `Payments` aka Outgoing)?
* [x] Ensure that SCI can retrieve the gas-cost alongside the withdraw transactions themselves
* [x] Ensure that deposit top-ups are listed within the `Payments`/Outgoing list
* [x] Ensure we retrieve the deposit top-up gas cost alongside the operations themselves
* [x] Ensure that deposit withdraws are listed within the `Incomes`/Incoming list
* [x] Implement migrations from `Income`, `Payment` and `DepositPayment`

#### Considerations
* Refactor the `Income` and `Payment` records to unify them? [ yes ]
* Extend `Income` as a storage for top-ups (both ETH and GNT)?  [ no ]
* Extend `Payment` as a storage for withdraws (both ETH and GNT)?  [ no ]
* Don't unify the models but use union queries when constructing lists?  [ no ]
* Does stopping and/or restarting Golem interfere with any of the above functionality elements?  [ shouldn't ]
* We won't be replacing "Deposit Payment" as it represents the other side of the equation

### User Interface
https://projects.invisionapp.com/share/9MRIMPZJNWY#/screens/357819415_transactions-History_Copy_9

#### New transaction db model
Specified in #4197 

#### Updated application modules
* Payment history
* Incomes history
* `ReportComputedTask` message handler / adding awaiting Income records
* Post-verification handler (adding outgoing Payments)
* Outgoing payments processing
* Incoming payment handler
* Outgoing deposit processing

## Dependencies
* updates to SCI

### Sub-components
_Define and add links to sub-components_
* ?

### Blockers
_For any issues that block this issue, add links_
* ?

#### Base test process
** Single feature + Smoke Test

### New feature tests
_Add test scenarios for the new feature_

#### ETH top-up
* ETH Top-up is made
* [ Transaction is confirmed ]
* ETH Top-up is present in "All" transactions
* ETH Top-up is present in "Incoming" transactions

#### GNT top-up
* GNT Top-up is made
* [ Transaction is confirmed ]
* GNT Top-up is present in "All" transactions
* GNT Top-up is present in "Incoming" transactions

#### ETH withdraw
* ETH withdraw is made from Golem
* [ transaction is confirmed ]
* ETH withdraw is present in "All" transactions
* ETH withdraw is present in "Outgoing" transactions

#### GNT withdraw
* GNT withdraw is made from Golem
* [ transaction is confirmed ]
* GNT withdraw is present in "All" transactions
* GNT withdraw is present in "Outgoing" transactions

#### ETH withdraw fails 
* try to perform ETH withdraw with insufficient funds
* no new ETH withdraw records are added to "All" transactions
* no new ETH withdraw records are added to "Outgoing" transactions

#### GNT withdraw fails 
* try to perform GNT withdraw with insufficient funds
* no new GNT withdraw records are added to "All" transactions
* no new GNT withdraw records are added to "Outgoing" transactions

#### Deposit payment
* Request a task using Concent
* Deposit payment should appear in "All" transactions as outgoing (with negated amount)
* Deposit payment should appear in "Outgoing" transactions (with negated amount)
* Deposit payment should still apear as a top-up in the Deposit transaction history

### Possible regressions
* Payments
* Incomes
* any functionality directly related to payments - both incoming or outgoing

### Development
* [ ] Feature implemented
* [ ] Feature unit/integration tests implemented

### Dev QA
* [x] Basic tests by the developer pass
* [x] Unit tests pass
* [x] Golem integration tests pass
* [ ] Concent integration tests pass
* [ ] Concent acceptance tests pass

### QA team
* [ ] ETH top-up
* [ ] GNT top-up
* [ ] ETH withdraw
* [ ] GNT withdraw
* [ ] ETH withdraw failure
* [ ] GNT withdraw failure
* [ ] Smoke test

## Issues encountered during QA
_When adding an issue here, please update testing scenarios and QA progress above_
* [ ] link to issue... 
* [ ] ...
