### ISSUE TITLE
Subtasks list in CLI

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/clay#4666]
## Rationale
There is a CLI command tasks subtasks <task_id>. The way it works now is fine with Blender but not with VbR. It does not show how many instances/jobs/executions of given subtask there was. The simplest way is to add a subtask name to the result table.
The point is that subtask_id does not refer to a subtask, rather to a job - single execution of a given subtask. And let it be so. The problem is more visible for VbR. A user requests 3 subtasks and it sees 6 subtasks on the list. The idea is to use a subtask name. The user still will see 6 results but grouped. And the message for the user is: you have requested 3 subtasks but here are 6 jobs because of VbR.

### Functional specification
This is an improvement to CLI tasks subtasks <task_id> command. Add a leading column to subtasks results: subtask name. By default results are to be sorted by subtask name (or maybe subtask name, subtask id). Also add explicit option for sorting: subtask name.

### User Interface
There is no change to the user flow. There is only one more option for sorting: tasks subtasks <task_id> --sort subtask_name.

### Technical specification
That may require to extend RPC command, but I am not sure.

## Dependencies
1. If RPC command will be extended then it will affect new Golem CLI.
2. If RPC command will be extended then it will affect Electron GUI.
3. Similar changes should be provided in new Golem CLI. It will be requested in a separate issue.
4. Similar changes should be provided in Electron GUI. At the moment we do not show subtasks of gWASM tasks so we will not do this for now.
5. Please update also CLI help (sort option).
6. Please update also Golem docs.

### Development
* [ ] Feature implemented
* [ ] Feature unit/integration tests implemented

### Dev QA
* [ ] Basic tests by the developer pass
* [ ] Unit tests pass
* [ ] Golem integration tests pass
* [ ] Concent integration tests pass
* [ ] Concent acceptance tests pass

**Please choose the priority label for QA. It is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

### QA team
* [ ] Base scenario passes
* [ ] Additional test 1 passes... 
* [ ] ... 

## Issues encountered during QA
_When adding an issue here, please update testing scenarios and QA progress above_
* [ ] link to issue... 
* [ ] ...
